<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="xidp-ind-apt047" name="TestCase 051" tests="8" failures="8" timestamp="17 Aug 2017 07:47:05 GMT" time="0.244" errors="0">
  <testcase name="SuiteOneCaseTwoTest" time="0.001" classname="com.XIPL.SuiteOne.TC050">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="8">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 8
	at com.XIPL.SuiteOne.TC050.SuiteOneCaseTwoTest(TC050.java:123)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- SuiteOneCaseTwoTest -->
  <testcase name="SuiteOneCaseTwoTest" time="0.001" classname="com.XIPL.SuiteOne.TC050">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="9">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 9
	at com.XIPL.SuiteOne.TC050.SuiteOneCaseTwoTest(TC050.java:123)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- SuiteOneCaseTwoTest -->
  <testcase name="SuiteOneCaseTwoTest" time="0.001" classname="com.XIPL.SuiteOne.TC050">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="10">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 10
	at com.XIPL.SuiteOne.TC050.SuiteOneCaseTwoTest(TC050.java:123)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- SuiteOneCaseTwoTest -->
  <testcase name="SuiteOneCaseTwoTest" time="0.001" classname="com.XIPL.SuiteOne.TC050">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="11">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 11
	at com.XIPL.SuiteOne.TC050.SuiteOneCaseTwoTest(TC050.java:123)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- SuiteOneCaseTwoTest -->
  <testcase name="SuiteOneCaseTwoTest" time="0.001" classname="com.XIPL.SuiteOne.TC050">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="12">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 12
	at com.XIPL.SuiteOne.TC050.SuiteOneCaseTwoTest(TC050.java:123)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- SuiteOneCaseTwoTest -->
  <testcase name="SuiteOneCaseTwoTest" time="0.001" classname="com.XIPL.SuiteOne.TC050">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="13">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 13
	at com.XIPL.SuiteOne.TC050.SuiteOneCaseTwoTest(TC050.java:123)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- SuiteOneCaseTwoTest -->
  <testcase name="SuiteOneCaseTwoTest" time="0.001" classname="com.XIPL.SuiteOne.TC050">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="14">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 14
	at com.XIPL.SuiteOne.TC050.SuiteOneCaseTwoTest(TC050.java:123)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- SuiteOneCaseTwoTest -->
  <testcase name="SuiteOneCaseTwoTest" time="0.009" classname="com.XIPL.SuiteOne.TC050">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="15">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 15
	at com.XIPL.SuiteOne.TC050.SuiteOneCaseTwoTest(TC050.java:123)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- SuiteOneCaseTwoTest -->
</testsuite> <!-- TestCase 051 -->
